import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
const org='11111111-1111-4111-8111-111111111111';
test('manager publishes frozen requirements, preserves local/server conflict and explicitly resolves; completion guarded through UI and BFF',async({page})=>{
 if(!process.env.SEED_PASSWORD)throw Error('Private test credentials required');
 await page.goto('/sign-in');await page.getByLabel('Email',{exact:true}).fill('manager.north@example.test');await page.getByLabel('Password',{exact:true}).fill(process.env.SEED_PASSWORD);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:/Projects/})).toBeVisible();
 const origin=new URL(page.url()).origin;const headers={origin,'idempotency-key':randomUUID()};const created=await page.request.post(`/bff/v1/organizations/${org}/projects`,{headers,data:{name:'Task06 browser '+randomUUID().slice(0,8),description:'Isolated fixture',address:'Test site',status:'active'}});expect(created.ok()).toBe(true);const project=await created.json();const path=`/bff/v1/organizations/${org}/projects/${project.id}/checklist`;
 await page.goto(`/org/${org}/projects/${project.id}`);await page.getByRole('button',{name:'Manage template versions'}).click();await page.getByLabel('Title',{exact:true}).fill('Browser requirements '+project.id.slice(0,8));await page.getByLabel('Question 1',{exact:true}).fill('Final check');await page.getByLabel('Minimum photos',{exact:true}).fill('0');await page.getByRole('button',{name:'Publish version',exact:true}).click();await expect(page.getByRole('button',{name:'Publish version',exact:true})).toBeVisible();
 const versions=await (await page.request.get(`/bff/v1/organizations/${org}/checklist-templates`)).json();const template=versions.templates.find((t:{title:string})=>t.title==='Browser requirements '+project.id.slice(0,8));expect(template).toBeTruthy();await page.getByRole('combobox',{name:'Template version',exact:true}).selectOption(`${template.id}:1`);await page.getByRole('button',{name:'Start frozen checklist'}).click();await expect(page.getByText('Frozen template version 1.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Complete project after requirements check'}).click();await expect(page.getByRole('alert').filter({hasText:'COMPLETION_REQUIRED'})).toBeVisible();
 const run=(await (await page.request.get(path)).json()).run;
 await page.getByLabel('Final check',{exact:true}).fill('My local draft');
 const server=await page.request.post(path,{headers:{origin,'idempotency-key':randomUUID()},data:{kind:'answer',runId:run.id,questionId:template.questions[0].id,text:'Concurrent server answer',mediaIds:[],baseVersion:0}});expect(server.ok()).toBe(true);
 await page.getByRole('button',{name:'Save answer',exact:true}).click();await expect(page.getByText('Your local answer: My local draft.',{exact:false})).toBeVisible();await expect(page.getByText('Current known server v1: Concurrent server answer.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Resolve with my edited answer'}).click();await expect(page.getByText('Your local answer:',{exact:false})).toHaveCount(0);expect((await (await page.request.get(path)).json()).run.answers[0].text).toBe('My local draft');
 // Lose an actual committed response; retry uses the same frozen payload/key once.
 let first=true;const submitted:string[]=[];await page.route(`**${path}`,async route=>{if(route.request().method()!=='POST'){await route.continue();return;}submitted.push(route.request().headers()['idempotency-key']!);const response=await route.fetch();if(first){first=false;await route.fulfill({status:502,contentType:'application/json',body:JSON.stringify({code:'UPSTREAM_UNAVAILABLE',message:'Lost reply',requestId:'test'})});}else await route.fulfill({response});});
 await page.getByLabel('Final check',{exact:true}).fill('Retried exact answer');await page.getByRole('button',{name:'Save answer',exact:true}).click();await expect(page.getByRole('button',{name:'Retry frozen answer'})).toBeVisible();await expect(page.getByLabel('Final check',{exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry frozen answer'}).click();await expect(page.getByRole('button',{name:'Save answer',exact:true})).toBeVisible();expect(submitted).toHaveLength(2);expect(submitted[0]).toBe(submitted[1]);await page.unroute(`**${path}`);
 expect((await (await page.request.get(path)).json()).run.answers[0].version).toBe(3);
 await page.getByRole('button',{name:'Complete project after requirements check'}).click();await expect(page.getByRole('button',{name:'Complete project after requirements check'})).toBeDisabled();await expect(page.getByLabel('Final check',{exact:true})).toBeDisabled();
 await page.screenshot({path:`${process.env.TEST_ARTIFACT_DIR ?? '.local/task06'}/browser-complete.png`,fullPage:true});
});
