import { readFile, writeFile } from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
const output = new URL('./src/generated.ts', import.meta.url);
const generated = '// Generated by pnpm contracts:generate. Do not edit.\n' + astToString(await openapiTS(new URL('./openapi/openapi.json', import.meta.url)));
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== generated) throw new Error('OpenAPI client drift. Run pnpm contracts:generate');
  console.log('Generated contract matches OpenAPI source.');
} else { await writeFile(output, generated); }
